### ISSUE TITLE
API call for createOrUpdate should not create a new version if code has not changed

### ISSUE THREAD

**Issue by acrodrig** [val-town/val-town-product#185]
In order to have an idempotent script, it would be nice if I can call the `createOrUpdate` API and it would NOT create a new version if the code (or any other parameter) has changed. As it is, it will create a new (empty) version (see screenshot) which is sort of useless.

![image](https://github.com/user-attachments/assets/4d6a6cc9-167d-448a-8e43-356cb15e01cb)

**Comment by sophiehouser** [comment]
Hey @acrodrig, thanks for your message! We've updated the endpoint so it won't create a new version if the code, type, privacy, name and readme all stay the same.
